export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';

export const FETCH_FACT = 'FETCH_FACT';
export const REQUESTED_FACT_SUCCEEDED = 'REQUESTED_FACT_SUCCEEDED';
export const REQUESTED_FACT_FAILED = 'REQUESTED_FACT_FAILED';

export const FETCH_DOG = 'FETCH_DOG';
export const REQUESTED_DOG_SUCCEEDED = 'REQUESTED_DOG_SUCCEEDED';
export const REQUESTED_DOG_FAILED = 'REQUESTED_DOG_FAILED';