export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';

export const FETCH_JOKE = 'FETCH_JOKE';
export const REQUESTED_JOKE_SUCCEEDED = 'REQUESTED_JOKE_SUCCEEDED';
export const REQUESTED_JOKE_FAILED = 'REQUESTED_JOKE_FAILED';

export const FETCH_DOG = 'FETCH_DOG';
export const REQUESTED_DOG_SUCCEEDED = 'REQUESTED_DOG_SUCCEEDED';
export const REQUESTED_DOG_FAILED = 'REQUESTED_DOG_FAILED';

export const FETCH_POSTS = 'FETCH_POSTS';
export const CHANGE_SORT_ORDER = 'CHANGE_SORT_ORDER';
export const REQUESTED_POSTS_SUCCEEDED = 'REQUESTED_POSTS_SUCCEEDED';
export const REQUESTED_POSTS_FAILED = 'REQUESTED_POSTS_FAILED';

export const FETCH_COUNTRIES = 'FETCH_COUNTRIES';
export const FILTER_COUNTRIES = 'FILTER_COUNTRIES';
export const REQUESTED_COUNTRIES_SUCCEEDED = 'REQUESTED_COUNTRIES_SUCCEEDED';
export const REQUESTED_COUNTRIES_FAILED = 'REQUESTED_COUNTRIES_FAILED';
